name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        env:
          CI: true
        run: |
          cd tata-backend
          npm install
      - name: test
        run: |
          cd tata-backend
          npm run test