name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Open tata-backend
        run: |
          ls -la
          cd tata-backend
          ls -la
      - name: npm ci
        env:
          CI: true
        run: |
          npm install
      - name: test
        run: |
          npm run test